// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Both `DATABASE_URL` and `DIRECT_URL` should be set in `.env` (loaded via dotenv above).
    // Prisma ORM 7 only supports `url` and `shadowDatabaseUrl` here — not `directUrl` on the
    // datasource (see https://www.prisma.io/docs/orm/reference/prisma-config-reference).
    // Use the **direct** connection for CLI commands (migrate, introspect) when your
    // `DATABASE_URL` targets a pooler (e.g. Supabase + PgBouncer). Use `DATABASE_URL` in
    // your app with the database driver / Prisma adapter at runtime.
    url: env("DIRECT_URL"),
  },
});
