import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Declaration of Consent",
  description:
    "Consent to automated API execution and copy-trading features on TradeICT Earner.",
};

const docClass =
  "space-y-6 text-[15px] leading-relaxed text-white/85 [&_strong]:font-semibold [&_strong]:text-white";

export default function DeclarationOfConsentPage() {
  return (
    <article className={docClass}>
      <header className="space-y-2 border-b border-white/10 pb-8">
        <h1 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
          Declaration of Consent
        </h1>
        <p className="text-sm text-white/50">Last updated: May 3, 2026</p>
        <p className="text-sm text-white/60">
          By creating an account, connecting an exchange or broker via API, or enabling automated
          execution—including strategy subscription or copy-trading features—you acknowledge and
          consent to the terms below in connection with TradeICT Earner, operated by TradeICT
          (“we,” “us,” or “our”).
        </p>
      </header>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-white">1. Nature of consent</h2>
        <p>
          This Declaration supplements our Terms of Service, Privacy Policy, Risk Disclaimer, and
          End-User License Agreement. Capitalized terms used here have the meanings given in those
          documents unless otherwise defined.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-white">2. SaaS execution via API</h2>
        <p>
          You expressly consent to our accessing your designated exchange or broker accounts through
          API keys or other authorized integration methods that you provide or approve, solely for
          the purpose of delivering the Service—including placing, modifying, or canceling orders and
          performing related operations consistent with the features you activate.
        </p>
        <p>
          You understand that API connectivity may be continuous while enabled and that disabling keys
          at your exchange or disconnecting the integration will affect Service behavior.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-white">3. Automated and algorithmic execution</h2>
        <p>
          You consent to automated processing of trading instructions generated by the software,
          including algorithmic rules, scheduled logic, and—where you opt in—signals or actions
          derived from strategies or copy-trading workflows you select. You acknowledge that such
          automation may execute trades without separate manual confirmation for each order, subject
          to settings available in the Service and limits imposed by your exchange.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-white">4. Non-custodial funds</h2>
        <p>
          You acknowledge that <strong>TradeICT Earner does not custody your trading funds</strong>.
          Assets remain with third-party exchanges or brokers under their terms. You maintain control
          of withdrawal rights subject to those venues’ rules and your API permissions.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-white">5. Risk acceptance</h2>
        <p>
          You confirm that you have read our Risk Disclaimer, that trading cryptocurrencies and
          using automated execution involves substantial risk of loss including total loss of capital,
          and that you voluntarily assume all risks associated with trading in accounts you control.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-white">6. No advice</h2>
        <p>
          You agree that we do not provide personalized investment advice. Any strategies, metrics, or
          social signals shown in the Service are informational or operational tools only; you alone
          decide whether to enable automation and with what parameters.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-white">7. Data processing</h2>
        <p>
          You consent to the collection and processing of personal and technical data as described in
          our Privacy Policy, including processing necessary to authenticate you, operate API
          connectivity, secure the Service, and comply with law.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-white">8. Withdrawal of consent</h2>
        <p>
          Where processing is based on consent under applicable law, you may withdraw consent by
          disconnecting integrations, deleting your account where available, or contacting us,
          subject to legal retention obligations. Withdrawal may prevent us from providing some or
          all features.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-white">9. Electronic agreement</h2>
        <p>
          You agree that your electronic acceptance (including clicking “I agree,” enabling API
          trading, or continued use where permitted by law) constitutes a binding signature for
          purposes of this Declaration where electronic signatures are recognized.
        </p>
      </section>

      <footer className="border-t border-white/10 pt-8 text-sm text-white/50">
        <p>
          If you do not agree with this Declaration, do not connect trading APIs or enable automated
          execution features.
        </p>
      </footer>
    </article>
  );
}
